version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dbahn-postgres
    environment:
      POSTGRES_DB: DBahn-berlin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin4321
    ports:
      - "6543:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      - ./sql/star_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    networks:
      - dbahn-network
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 2s
      timeout: 5s
      retries: 10

  etl: 
    build: .
    container_name: dbahn-etl
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - ./data/raw/DBahn-berlin:/app/data/raw/DBahn-berlin
    environment:
      DB_HOST: dbahn-postgres   # must match container_name
      DB_PORT: 5432
      DB_NAME: DBahn-berlin
      DB_USER: admin
      DB_PASSWORD: admin4321
    networks:
      - dbahn-network
    command: python -u src/main.py
    restart: on-failure

volumes:
  postgres_data: 

networks:
  dbahn-network:
    driver: bridge
    
